"""
CLAUDE-P27-B: adopts Flask-Migrate/Alembic for the NEXT schema change
onward (models.py's own docstring already flagged a third genuine
schema change as the trigger). Does not replace app.py's existing
hand-rolled create_all() + _migrate_users_* functions, which remain
what actually creates/migrates the already-deployed schema at boot.

Every migrations/versions/*.py revision is hand-written, not
autogenerated -- _register_database() always runs create_all() first
(even under the `flask db` CLI), so autogenerate never sees a diff.
This test proves the FULL hand-written revision CHAIN (walked from
None to head, not one hardcoded file -- CLAUDE-LIVE-VERIFICATION-
ACCOUNT-MECHANISM-01 added a second revision, d67fbff1ba5e, on top of
the original f8620fa70917 baseline, and any future revision extends
this same chain without needing this test touched again) produces
byte-identical schema to what create_all() + the hand-migrations
actually produce, the same check performed manually and recorded in
migrations/README before stamping the live database.

Path B below deliberately runs each revision's own upgrade() against a
raw SQLAlchemy engine via Alembic's MigrationContext/Operations
directly -- NOT flask_migrate.upgrade() against a second throwaway
Flask app. An earlier version of this test tried that second app
approach and it corrupted later, unrelated tests in the same pytest
process (test_password_reset.py, test_auth_security_logging.py, etc.
started failing only when run in the same session as this file) --
registering Migrate/db.init_app a second time on models.py's shared,
module-level `db = SQLAlchemy()` singleton left some part of its
internal engine-registry state pointed at this test's own throwaway
database. Raw Alembic, with no Flask app or shared `db` object
involved at all, avoids that class of contamination entirely.

Run via:

    python -m unittest discover -s tests -v
"""
from __future__ import annotations

import shutil
import sqlite3
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import sqlalchemy as sa
from alembic.migration import MigrationContext
from alembic.operations import Operations

import config

MIGRATIONS_VERSIONS_DIR = Path(__file__).resolve().parent.parent / "migrations" / "versions"


class FlaskMigrateRegistrationTests(unittest.TestCase):
    def test_migrate_extension_is_registered_on_the_app(self):
        import app as app_module

        flask_app = app_module.create_app("testing")
        self.assertIn("migrate", flask_app.extensions)


class BaselineMigrationSchemaTests(unittest.TestCase):
    def setUp(self):
        self.tmp_dir = Path(tempfile.mkdtemp(prefix="beehive_test_migration_baseline_"))

    def tearDown(self):
        shutil.rmtree(self.tmp_dir, ignore_errors=True)

    def _schema_text(self, db_path: Path):
        conn = sqlite3.connect(db_path)
        rows = conn.execute(
            # alembic_version excluded deliberately, not an oversight:
            # it is Alembic's OWN revision-bookkeeping table, created
            # only by the migration path (Path B, via flask_migrate.
            # upgrade()), never by create_all() (Path A) -- a real,
            # expected, already-documented structural difference between
            # a fresh create_all() install and an alembic-upgraded one
            # (migrations/README's own "stamped, not upgraded" note),
            # not a domain-schema mismatch this test exists to catch.
            "SELECT type, name, sql FROM sqlite_master "
            "WHERE type IN ('table', 'index') AND name NOT LIKE 'sqlite_%' AND name != 'alembic_version' "
            "ORDER BY type, name",
        ).fetchall()
        conn.close()
        return rows

    def _load_revision_chain(self) -> list:
        """Discovers every migrations/versions/*.py file, reads its
        `revision`/`down_revision` module attributes (real parsing, not a
        hardcoded file list), and returns the modules ordered from the
        root (down_revision=None) to head -- one linear chain, matching
        this repo's own migrations/README ("a normal Alembic revision"
        for every schema change so far, never branching)."""
        import importlib.util

        by_revision = {}
        down_revision_of = {}
        for path in sorted(MIGRATIONS_VERSIONS_DIR.glob("*.py")):
            spec = importlib.util.spec_from_file_location(path.stem, path)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            by_revision[module.revision] = module
            down_revision_of[module.revision] = module.down_revision

        chain = []
        current = next(rev for rev, down in down_revision_of.items() if down is None)
        while current is not None:
            chain.append(by_revision[current])
            current = next((rev for rev, down in down_revision_of.items() if down == current), None)
        self.assertEqual(len(chain), len(by_revision), "revision chain is not a single linear sequence")
        return chain

    def test_baseline_migration_matches_create_all_schema(self):
        # Path A: exactly what a fresh install's create_all() +
        # existing hand-migrations produce (app.py's real boot path).
        import app as app_module

        # SQLALCHEMY_DATABASE_URI is bound to the engine at db.init_app()
        # time (inside create_app) -- overriding app.config afterward is
        # too late, same reason RATELIMIT_ENABLED/WTF_CSRF_ENABLED must
        # be patched on the config CLASS before create_app() runs.
        create_all_db = self.tmp_dir / "via_create_all.db"
        with patch.object(config.TestingConfig, "SQLALCHEMY_DATABASE_URI", f"sqlite:///{create_all_db}"):
            flask_app = app_module.create_app("testing")
        with flask_app.app_context():
            from models import db

            db.create_all()

        # Path B: apply every hand-written revision's own upgrade(), in
        # chain order (None -> ... -> head), directly against a raw
        # connection via Alembic's MigrationContext/Operations -- no
        # Flask app, no Migrate extension, no shared `db` object touched
        # at all (see this test's own module docstring for why: an
        # earlier version used flask_migrate.upgrade() against a second
        # throwaway Flask app and that corrupted later, unrelated tests
        # in the same pytest process).
        migration_db = self.tmp_dir / "via_migration.db"
        engine = sa.create_engine(f"sqlite:///{migration_db}")
        with engine.connect() as conn:
            ctx = MigrationContext.configure(conn)
            with Operations.context(ctx):
                for module in self._load_revision_chain():
                    module.upgrade()
            conn.commit()

        self.assertEqual(self._schema_text(create_all_db), self._schema_text(migration_db))


if __name__ == "__main__":
    unittest.main()
