"""
CLAUDE-P27-B: adopts Flask-Migrate/Alembic for the NEXT schema change
onward (models.py's own docstring already flagged a third genuine
schema change as the trigger). Does not replace app.py's existing
hand-rolled create_all() + _migrate_users_* functions, which remain
what actually creates/migrates the already-deployed schema at boot.

migrations/versions/f8620fa70917_..._baseline_schema...py is hand-
written, not autogenerated -- _register_database() always runs
create_all() first (even under the `flask db` CLI), so autogenerate
never sees a diff. This test proves that hand-written baseline
produces byte-identical schema to what create_all() + the hand-
migrations actually produce, the same check performed manually and
recorded in migrations/README before stamping the live database.

Run via:

    python -m unittest discover -s tests -v
"""
from __future__ import annotations

import importlib.util
import shutil
import sqlite3
import tempfile
import unittest
from pathlib import Path

import sqlalchemy as sa
from alembic.migration import MigrationContext
from alembic.operations import Operations
from unittest.mock import patch

import config

BASELINE_MIGRATION_PATH = Path(__file__).resolve().parent.parent / (
    "migrations/versions/f8620fa70917_baseline_schema_claude_p27_b_users_.py"
)


class FlaskMigrateRegistrationTests(unittest.TestCase):
    def test_migrate_extension_is_registered_on_the_app(self):
        import app as app_module

        flask_app = app_module.create_app("testing")
        self.assertIn("migrate", flask_app.extensions)


class BaselineMigrationSchemaTests(unittest.TestCase):
    def setUp(self):
        self.tmp_dir = Path(tempfile.mkdtemp(prefix="beehive_test_migration_baseline_"))

    def tearDown(self):
        shutil.rmtree(self.tmp_dir, ignore_errors=True)

    def _schema_text(self, db_path: Path):
        conn = sqlite3.connect(db_path)
        rows = conn.execute(
            "SELECT type, name, sql FROM sqlite_master "
            "WHERE type IN ('table', 'index') AND name NOT LIKE 'sqlite_%' "
            "ORDER BY type, name",
        ).fetchall()
        conn.close()
        return rows

    def test_baseline_migration_matches_create_all_schema(self):
        # Path A: exactly what a fresh install's create_all() +
        # existing hand-migrations produce (app.py's real boot path).
        import app as app_module

        # SQLALCHEMY_DATABASE_URI is bound to the engine at db.init_app()
        # time (inside create_app) -- overriding app.config afterward is
        # too late, same reason RATELIMIT_ENABLED/WTF_CSRF_ENABLED must
        # be patched on the config CLASS before create_app() runs.
        create_all_db = self.tmp_dir / "via_create_all.db"
        with patch.object(config.TestingConfig, "SQLALCHEMY_DATABASE_URI", f"sqlite:///{create_all_db}"):
            flask_app = app_module.create_app("testing")
        with flask_app.app_context():
            from models import db

            db.create_all()

        # Path B: apply the hand-written baseline migration's upgrade()
        # directly against a raw connection -- no Flask app involved.
        migration_db = self.tmp_dir / "via_migration.db"
        spec = importlib.util.spec_from_file_location("baseline_migration", BASELINE_MIGRATION_PATH)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        engine = sa.create_engine(f"sqlite:///{migration_db}")
        with engine.connect() as conn:
            ctx = MigrationContext.configure(conn)
            with Operations.context(ctx):
                module.upgrade()
            conn.commit()

        self.assertEqual(self._schema_text(create_all_db), self._schema_text(migration_db))


if __name__ == "__main__":
    unittest.main()
