"""
CLAUDE-P31 -- persistence and lifecycle for the Organizational Security
Department's policy corpus: source policies, extracted statements,
proposed controls, governed Q&A, and the ratified baseline version
history.

Honesty boundary (see services/security_policy.py's module docstring
for the full explanation): this repository has no multi-organization
model, so SecurityGovernanceStore manages exactly ONE global record --
a single deployment-wide security governance file, not one per tenant.
Same flat-JSON-over-a-database choice this project has made everywhere
else (tools/dependency_fit.py), just at a different scope than
CaseWorkspaceStore's per-project files.

Deliberately conservative about automation: policy-statement extraction
and control-mapping proposals are recorded as plain governed data
entered by a human security officer through the Security Department
workspace -- NOT generated by a new AI prompt. Part IV's "Do not allow
machine extraction to activate controls automatically" is honored by
going a step further and not introducing machine extraction into this
pipeline at all this stage (consistent with this codebase's standing
caution around services/bhive_parser.py's already-fragile, adversarially
-tuned prompts -- see that module's own history). AI-assisted extraction
remains a real, named, specified-but-unbuilt future capability, not
something silently implied to exist.
"""
from __future__ import annotations

import json
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _new_id() -> str:
    return str(uuid.uuid4())


class SecurityGovernanceError(Exception):
    """Raised for invalid security-governance operations."""


# -- Q&A answer authority states (Part V) ------------------------------------
QA_STATUS_ESTABLISHED_BY_POLICY = "established_by_policy"
QA_STATUS_AUTHORIZED_ANSWER = "authorized_answer"
QA_STATUS_PROVISIONAL_PENDING_APPROVAL = "provisional_pending_approval"
QA_STATUS_UNRESOLVED = "unresolved"
QA_STATUS_CONFLICTING = "conflicting"
QA_STATUS_NOT_TECHNICALLY_SUPPORTED = "not_technically_supported"

KNOWN_QA_STATUSES = (
    QA_STATUS_ESTABLISHED_BY_POLICY,
    QA_STATUS_AUTHORIZED_ANSWER,
    QA_STATUS_PROVISIONAL_PENDING_APPROVAL,
    QA_STATUS_UNRESOLVED,
    QA_STATUS_CONFLICTING,
    QA_STATUS_NOT_TECHNICALLY_SUPPORTED,
)

# -- Baseline ratification states (Part XIV) ---------------------------------
BASELINE_STATUS_DRAFT = "draft"
BASELINE_STATUS_UNDER_REVIEW = "under_review"
BASELINE_STATUS_APPROVED = "approved"
BASELINE_STATUS_ACTIVE = "active"
BASELINE_STATUS_SUPERSEDED = "superseded"
BASELINE_STATUS_WITHDRAWN = "withdrawn"

KNOWN_BASELINE_STATUSES = (
    BASELINE_STATUS_DRAFT,
    BASELINE_STATUS_UNDER_REVIEW,
    BASELINE_STATUS_APPROVED,
    BASELINE_STATUS_ACTIVE,
    BASELINE_STATUS_SUPERSEDED,
    BASELINE_STATUS_WITHDRAWN,
)

# Provenance kinds a ProposedControl/baseline control-decision may cite --
# "Never disguise an application recommendation as a customer policy
# requirement" (Part III) is enforced by making this an explicit,
# required, closed field on every control decision, not an afterthought.
CONTROL_SOURCE_POLICY_STATEMENT = "policy_statement"
CONTROL_SOURCE_QA_ENTRY = "qa_entry"
CONTROL_SOURCE_MANDATORY_FLOOR = "mandatory_floor"
CONTROL_SOURCE_ARCHIOSK_DEFAULT = "archiosk_default"

KNOWN_CONTROL_SOURCES = (
    CONTROL_SOURCE_POLICY_STATEMENT,
    CONTROL_SOURCE_QA_ENTRY,
    CONTROL_SOURCE_MANDATORY_FLOOR,
    CONTROL_SOURCE_ARCHIOSK_DEFAULT,
)


@dataclass
class SourcePolicy:
    """The preserved original -- 'Original Written Policy != Machine
    Interpretation != Proposed Application Controls != Ratified
    Executable Security Baseline' (Part III). Never mutated once
    recorded; a revised policy is a new SourcePolicy row with
    superseded_version_id pointing back, the same denormalized-
    predecessor-pointer pattern Source.supersedes_source_id already
    uses in case_workspace.py."""

    id: str
    title: str
    issuing_organization: str
    ingested_at: str
    ingested_by: str
    file_path: Optional[str] = None
    file_hash: Optional[str] = None
    policy_owner: Optional[str] = None
    approving_authority: Optional[str] = None
    version: Optional[str] = None
    effective_date: Optional[str] = None
    expiry_date: Optional[str] = None
    superseded_version_id: Optional[str] = None
    jurisdiction: Optional[str] = None
    classification: Optional[str] = None


@dataclass
class PolicyStatement:
    """One human-extracted clause from a SourcePolicy -- deliberately
    human-entered, not machine-extracted, this stage (see module
    docstring)."""

    id: str
    source_policy_id: str
    clause_text: str
    extracted_at: str
    extracted_by: str
    clause_reference: Optional[str] = None  # e.g. "Section 4.2" -- free text, optional


@dataclass
class ProposedControl:
    """A human-proposed mapping from a PolicyStatement or QAEntry to one
    governed action + decision -- 'requires_confirmation' is always True
    until a security officer moves it into a BaselineVersion's own
    control_decisions via confirm_proposed_control, which is the one
    and only path that can flip it (Part IV: 'Do not allow machine
    extraction to activate controls automatically' -- there is no
    machine extraction here at all, and even a human-authored proposal
    doesn't self-activate)."""

    id: str
    action_id: str
    proposed_decision: str
    rationale: str
    proposed_at: str
    proposed_by: str
    source_type: str  # KNOWN_CONTROL_SOURCES
    source_id: Optional[str] = None  # PolicyStatement.id or QAEntry.id; None only for archiosk_default
    ambiguity_note: Optional[str] = None
    status: str = "proposed"  # proposed | confirmed | rejected


@dataclass
class QAEntry:
    """One governed customer Q&A record (Part V) -- every field the
    mandate itself requires is a real, separate field, not folded into
    free text, so authority/scope/status are each independently
    queryable and testable."""

    id: str
    question: str
    answer: str
    responding_person: str
    authority: str  # free text role/title -- e.g. "CISO", "Security Officer"
    recorded_at: str
    status: str = QA_STATUS_UNRESOLVED
    supporting_source: Optional[str] = None
    scope: Optional[str] = None
    effective_date: Optional[str] = None
    approved_by: Optional[str] = None
    approved_at: Optional[str] = None


@dataclass
class SecurityException:
    """A time-bounded, scoped loosening of an otherwise-more-restrictive
    decision (Part VI/VII) -- never able to exceed DECISION_ALLOW (see
    services.security_policy.evaluate_action's own ceiling logic).
    project_id=None means organization-wide; otherwise scoped to one
    project."""

    id: str
    action_id: str
    decision: str
    rationale: str
    granted_by: str
    granted_at: str
    expires_at: Optional[str] = None
    project_id: Optional[str] = None
    status: str = "active"  # active | expired | revoked


@dataclass
class BaselineVersion:
    """One ratified (or in-progress) organization security baseline.
    control_decisions maps action_id -> {"decision", "source_type",
    "source_id", "rationale"} -- every entry carries its own provenance,
    never a bare decision string."""

    id: str
    version_number: int
    created_at: str
    created_by: str
    status: str = BASELINE_STATUS_DRAFT
    control_decisions: dict = field(default_factory=dict)
    capability_impact_acknowledged_by: Optional[str] = None
    capability_impact_acknowledged_at: Optional[str] = None
    activated_by: Optional[str] = None
    activated_at: Optional[str] = None
    effective_date: Optional[str] = None
    previous_version_id: Optional[str] = None
    superseded_at: Optional[str] = None


@dataclass
class SecurityGovernanceRecord:
    """The one global record SecurityGovernanceStore reads/writes --
    same fully-automatic asdict()/**data round-trip ProjectWorkspace
    uses (services/case_workspace.py), for the same reason: every field
    added below stays trivially safe to persist without hand-written
    (de)serialization."""

    source_policies: list = field(default_factory=list)
    policy_statements: list = field(default_factory=list)
    proposed_controls: list = field(default_factory=list)
    qa_entries: list = field(default_factory=list)
    baselines: list = field(default_factory=list)
    exceptions: list = field(default_factory=list)
    learning_contribution_requests: list = field(default_factory=list)  # CLAUDE-P31 - see services.learning_governance
    version: int = 0


class SecurityGovernanceStore:
    """services/case_workspace.py's CaseWorkspaceStore pattern, applied
    to the ONE global security-governance record instead of one file per
    project_id."""

    _FILENAME = "security_governance.json"

    def __init__(self, store_path: str | Path):
        # A dedicated subdirectory, not a bare file directly in
        # store_path -- RequirementsRegistry.list_ids() globs "*.json"
        # in that exact directory to enumerate every project, so a
        # same-level file here would be silently (mis)treated as a
        # bogus project id "security_governance". Same reasoning as
        # workspace_sources/ and workspace_artifacts/ already living in
        # their own subdirectories rather than top-level files.
        self.store_path = Path(store_path) / "security_governance"
        self.store_path.mkdir(parents=True, exist_ok=True)

    def _path(self) -> Path:
        return self.store_path / self._FILENAME

    def get(self) -> SecurityGovernanceRecord:
        path = self._path()
        if not path.exists():
            return SecurityGovernanceRecord()
        data = json.loads(path.read_text(encoding="utf-8"))
        return SecurityGovernanceRecord(**data)

    def save(self, record: SecurityGovernanceRecord) -> SecurityGovernanceRecord:
        record.version += 1
        self._path().write_text(json.dumps(asdict(record), indent=2), encoding="utf-8")
        return record

    # -- source policies -----------------------------------------------------

    def record_source_policy(
        self, record: SecurityGovernanceRecord, title: str, issuing_organization: str, ingested_by: str,
        file_path: Optional[str] = None, file_hash: Optional[str] = None, policy_owner: Optional[str] = None,
        approving_authority: Optional[str] = None, version: Optional[str] = None,
        effective_date: Optional[str] = None, expiry_date: Optional[str] = None,
        jurisdiction: Optional[str] = None, classification: Optional[str] = None,
        superseded_version_id: Optional[str] = None,
    ) -> dict:
        if not title or not title.strip():
            raise SecurityGovernanceError("A source policy requires a title.")
        policy = SourcePolicy(
            id=_new_id(), title=title.strip(), issuing_organization=issuing_organization,
            ingested_at=_now(), ingested_by=ingested_by, file_path=file_path, file_hash=file_hash,
            policy_owner=policy_owner, approving_authority=approving_authority, version=version,
            effective_date=effective_date, expiry_date=expiry_date, jurisdiction=jurisdiction,
            classification=classification, superseded_version_id=superseded_version_id,
        )
        record.source_policies.append(asdict(policy))
        self.save(record)
        return asdict(policy)

    # -- policy statements -----------------------------------------------------

    def record_policy_statement(
        self, record: SecurityGovernanceRecord, source_policy_id: str, clause_text: str, extracted_by: str,
        clause_reference: Optional[str] = None,
    ) -> dict:
        if not any(p["id"] == source_policy_id for p in record.source_policies):
            raise SecurityGovernanceError(f"Source policy {source_policy_id!r} was not found.")
        if not clause_text or not clause_text.strip():
            raise SecurityGovernanceError("A policy statement requires clause text.")
        statement = PolicyStatement(
            id=_new_id(), source_policy_id=source_policy_id, clause_text=clause_text.strip(),
            extracted_at=_now(), extracted_by=extracted_by, clause_reference=clause_reference,
        )
        record.policy_statements.append(asdict(statement))
        self.save(record)
        return asdict(statement)

    # -- proposed controls -----------------------------------------------------

    def propose_control(
        self, record: SecurityGovernanceRecord, action_id: str, proposed_decision: str, rationale: str,
        proposed_by: str, source_type: str, source_id: Optional[str] = None, ambiguity_note: Optional[str] = None,
    ) -> dict:
        from services.security_policy import GOVERNED_ACTIONS, KNOWN_DECISIONS

        if action_id not in GOVERNED_ACTIONS:
            raise SecurityGovernanceError(f"{action_id!r} is not a recognized governed action.")
        if proposed_decision not in KNOWN_DECISIONS:
            raise SecurityGovernanceError(f"{proposed_decision!r} is not a recognized decision.")
        if source_type not in KNOWN_CONTROL_SOURCES:
            raise SecurityGovernanceError(f"{source_type!r} is not a recognized control source.")
        if source_type in (CONTROL_SOURCE_POLICY_STATEMENT, CONTROL_SOURCE_QA_ENTRY) and not source_id:
            raise SecurityGovernanceError(
                f"A {source_type!r}-sourced control proposal requires source_id -- "
                "never disguise an application recommendation as a customer policy requirement."
            )
        control = ProposedControl(
            id=_new_id(), action_id=action_id, proposed_decision=proposed_decision, rationale=rationale,
            proposed_at=_now(), proposed_by=proposed_by, source_type=source_type, source_id=source_id,
            ambiguity_note=ambiguity_note,
        )
        record.proposed_controls.append(asdict(control))
        self.save(record)
        return asdict(control)

    # -- Q&A ---------------------------------------------------------------

    def record_qa_entry(
        self, record: SecurityGovernanceRecord, question: str, answer: str, responding_person: str,
        authority: str, status: str = QA_STATUS_UNRESOLVED, supporting_source: Optional[str] = None,
        scope: Optional[str] = None, effective_date: Optional[str] = None,
    ) -> dict:
        if status not in KNOWN_QA_STATUSES:
            raise SecurityGovernanceError(f"{status!r} is not a recognized Q&A status.")
        if not question or not question.strip():
            raise SecurityGovernanceError("A Q&A entry requires a question.")
        entry = QAEntry(
            id=_new_id(), question=question.strip(), answer=answer, responding_person=responding_person,
            authority=authority, recorded_at=_now(), status=status, supporting_source=supporting_source,
            scope=scope, effective_date=effective_date,
        )
        record.qa_entries.append(asdict(entry))
        self.save(record)
        return asdict(entry)

    def approve_qa_entry(self, record: SecurityGovernanceRecord, qa_entry_id: str, approved_by: str) -> dict:
        entry = next((e for e in record.qa_entries if e["id"] == qa_entry_id), None)
        if entry is None:
            raise SecurityGovernanceError(f"Q&A entry {qa_entry_id!r} was not found.")
        entry["status"] = QA_STATUS_AUTHORIZED_ANSWER
        entry["approved_by"] = approved_by
        entry["approved_at"] = _now()
        self.save(record)
        return entry

    # -- baselines -----------------------------------------------------------

    def create_baseline_draft(self, record: SecurityGovernanceRecord, created_by: str) -> dict:
        next_version = (max((b["version_number"] for b in record.baselines), default=0)) + 1
        active = next((b for b in record.baselines if b["status"] == BASELINE_STATUS_ACTIVE), None)
        baseline = BaselineVersion(
            id=_new_id(), version_number=next_version, created_at=_now(), created_by=created_by,
            previous_version_id=active["id"] if active else None,
        )
        record.baselines.append(asdict(baseline))
        self.save(record)
        return asdict(baseline)

    def add_control_decision(
        self, record: SecurityGovernanceRecord, baseline_id: str, action_id: str, decision: str,
        source_type: str, actor: str, source_id: Optional[str] = None, rationale: Optional[str] = None,
    ) -> dict:
        from services.security_policy import GOVERNED_ACTIONS, KNOWN_DECISIONS

        baseline = next((b for b in record.baselines if b["id"] == baseline_id), None)
        if baseline is None:
            raise SecurityGovernanceError(f"Baseline {baseline_id!r} was not found.")
        if baseline["status"] not in (BASELINE_STATUS_DRAFT, BASELINE_STATUS_UNDER_REVIEW):
            raise SecurityGovernanceError(
                f"Baseline {baseline_id!r} is {baseline['status']!r} -- control decisions can only be "
                "added while a baseline is still draft or under review."
            )
        if action_id not in GOVERNED_ACTIONS:
            raise SecurityGovernanceError(f"{action_id!r} is not a recognized governed action.")
        if decision not in KNOWN_DECISIONS:
            raise SecurityGovernanceError(f"{decision!r} is not a recognized decision.")
        if source_type not in KNOWN_CONTROL_SOURCES:
            raise SecurityGovernanceError(f"{source_type!r} is not a recognized control source.")

        baseline["control_decisions"][action_id] = {
            "decision": decision, "source_type": source_type, "source_id": source_id,
            "rationale": rationale, "recorded_by": actor, "recorded_at": _now(),
        }
        self.save(record)
        return baseline

    def acknowledge_capability_impact(self, record: SecurityGovernanceRecord, baseline_id: str, actor: str) -> dict:
        """Part VIII: 'the security administrator must explicitly
        acknowledge material consequences before ratification' -- a
        required, recorded step; activate_baseline refuses without it."""
        baseline = next((b for b in record.baselines if b["id"] == baseline_id), None)
        if baseline is None:
            raise SecurityGovernanceError(f"Baseline {baseline_id!r} was not found.")
        baseline["capability_impact_acknowledged_by"] = actor
        baseline["capability_impact_acknowledged_at"] = _now()
        if baseline["status"] == BASELINE_STATUS_DRAFT:
            baseline["status"] = BASELINE_STATUS_UNDER_REVIEW
        self.save(record)
        return baseline

    def activate_baseline(
        self, record: SecurityGovernanceRecord, baseline_id: str, actor: str, effective_date: Optional[str] = None,
    ) -> dict:
        """A baseline becomes ACTIVE only after its capability impact has
        been acknowledged (Part VIII/XIV) -- 'a security baseline must
        not become active merely because policy documents were
        uploaded.' Supersedes whichever baseline was previously active,
        preserving it (never deleted) with superseded_at recorded."""
        baseline = next((b for b in record.baselines if b["id"] == baseline_id), None)
        if baseline is None:
            raise SecurityGovernanceError(f"Baseline {baseline_id!r} was not found.")
        if not baseline.get("capability_impact_acknowledged_by"):
            raise SecurityGovernanceError(
                "This baseline's capability impact has not been acknowledged yet -- "
                "acknowledge_capability_impact must be called before activation."
            )
        if baseline["status"] in (BASELINE_STATUS_ACTIVE, BASELINE_STATUS_WITHDRAWN, BASELINE_STATUS_SUPERSEDED):
            raise SecurityGovernanceError(f"Baseline {baseline_id!r} is already {baseline['status']!r}.")

        previously_active = next((b for b in record.baselines if b["status"] == BASELINE_STATUS_ACTIVE), None)
        if previously_active is not None:
            previously_active["status"] = BASELINE_STATUS_SUPERSEDED
            previously_active["superseded_at"] = _now()

        baseline["status"] = BASELINE_STATUS_ACTIVE
        baseline["activated_by"] = actor
        baseline["activated_at"] = _now()
        baseline["effective_date"] = effective_date or _now()
        self.save(record)
        return baseline

    def withdraw_baseline(self, record: SecurityGovernanceRecord, baseline_id: str, actor: str) -> dict:
        baseline = next((b for b in record.baselines if b["id"] == baseline_id), None)
        if baseline is None:
            raise SecurityGovernanceError(f"Baseline {baseline_id!r} was not found.")
        baseline["status"] = BASELINE_STATUS_WITHDRAWN
        self.save(record)
        return baseline

    def active_baseline(self, record: SecurityGovernanceRecord) -> Optional[dict]:
        return next((b for b in record.baselines if b["status"] == BASELINE_STATUS_ACTIVE), None)

    # -- exceptions ------------------------------------------------------------

    def grant_exception(
        self, record: SecurityGovernanceRecord, action_id: str, decision: str, rationale: str, granted_by: str,
        expires_at: Optional[str] = None, project_id: Optional[str] = None,
    ) -> dict:
        from services.security_policy import DECISION_ALLOW, GOVERNED_ACTIONS, KNOWN_DECISIONS

        if action_id not in GOVERNED_ACTIONS:
            raise SecurityGovernanceError(f"{action_id!r} is not a recognized governed action.")
        if decision not in KNOWN_DECISIONS:
            raise SecurityGovernanceError(f"{decision!r} is not a recognized decision.")
        exception = SecurityException(
            id=_new_id(), action_id=action_id, decision=decision, rationale=rationale, granted_by=granted_by,
            granted_at=_now(), expires_at=expires_at, project_id=project_id,
        )
        record.exceptions.append(asdict(exception))
        self.save(record)
        return asdict(exception)

    def revoke_exception(self, record: SecurityGovernanceRecord, exception_id: str) -> dict:
        exception = next((e for e in record.exceptions if e["id"] == exception_id), None)
        if exception is None:
            raise SecurityGovernanceError(f"Exception {exception_id!r} was not found.")
        exception["status"] = "revoked"
        self.save(record)
        return exception

    def active_exception_for(
        self, record: SecurityGovernanceRecord, action_id: str, project_id: Optional[str] = None,
    ) -> Optional[dict]:
        """The most specific still-active, non-expired exception for
        this action -- a project-scoped exception takes precedence over
        an organization-wide one for that same project (specific over
        general), matching how SecurityException.project_id=None reads
        as 'applies everywhere' rather than 'applies nowhere'."""
        now = _now()
        candidates = [
            e for e in record.exceptions
            if e["action_id"] == action_id and e["status"] == "active"
            and (e["expires_at"] is None or e["expires_at"] > now)
            and (e["project_id"] is None or e["project_id"] == project_id)
        ]
        if not candidates:
            return None
        project_scoped = [e for e in candidates if e["project_id"] == project_id and project_id is not None]
        return project_scoped[0] if project_scoped else candidates[0]

    # -- learning contribution requests (Part XI) -------------------------------
    # Thin persistence wrapper around services.learning_governance's pure
    # dataclass functions -- the lifecycle/authority logic lives there
    # (directly unit-testable with no store/IO involved); this class only
    # ever converts to/from the plain-dict shape this store's JSON file
    # already uses everywhere else.

    def create_learning_contribution_request(
        self, record: SecurityGovernanceRecord, project_id: str, source_zone: str, target_zone: str,
        candidate_description: str, requested_by: str,
    ) -> dict:
        from services.learning_governance import create_contribution_request

        request = create_contribution_request(
            project_id=project_id, source_zone=source_zone, target_zone=target_zone,
            candidate_description=candidate_description, requested_by=requested_by,
        )
        record.learning_contribution_requests.append(asdict(request))
        self.save(record)
        return asdict(request)

    def advance_learning_contribution_stage(
        self, record: SecurityGovernanceRecord, request_id: str, stage: str, actor: str,
    ) -> dict:
        from services.learning_governance import LearningContributionRequest, advance_stage

        stored = next((r for r in record.learning_contribution_requests if r["id"] == request_id), None)
        if stored is None:
            raise SecurityGovernanceError(f"Learning contribution request {request_id!r} was not found.")
        request = LearningContributionRequest(**stored)
        advance_stage(request, stage, actor)
        stored.update(asdict(request))
        self.save(record)
        return stored

    def decide_learning_contribution(
        self, record: SecurityGovernanceRecord, request_id: str, decision: str, decided_by: str, rationale: str,
    ) -> dict:
        from services.learning_governance import LearningContributionRequest, decide_contribution

        stored = next((r for r in record.learning_contribution_requests if r["id"] == request_id), None)
        if stored is None:
            raise SecurityGovernanceError(f"Learning contribution request {request_id!r} was not found.")
        request = LearningContributionRequest(**stored)
        decide_contribution(request, decision, decided_by, rationale)
        stored.update(asdict(request))
        self.save(record)
        return stored
