"""Baseline schema (CLAUDE-P27-B): users, password_reset_tokens

Hand-written, not autogenerated -- app.py's _register_database() always
runs db.create_all() on every app boot (including under the `flask db`
CLI), so `flask db migrate` never sees a diff to autogenerate against;
this describes the exact schema create_all() + the existing hand-
migrations already produce (verified against migrations/README's
scratch-copy check), for a truly fresh install going forward. Does NOT
change what actually runs at boot today -- create_all() and the two
_migrate_users_* functions in app.py are untouched. The already-
deployed database is `flask db stamp`-ed to this revision, not
upgraded through it (see migrations/README).

Revision ID: f8620fa70917
Revises:
Create Date: 2026-07-29 18:18:50.488426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8620fa70917'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        # collation="NOCASE" matches models.py's User.email exactly
        # (CLAUDE-P30) -- a case-insensitive UNIQUE constraint from a
        # fresh install, not just app-layer normalization.
        sa.Column("email", sa.String(length=255, collation="NOCASE"), nullable=True),
    )
    op.create_index("ix_users_username", "users", ["username"], unique=True)
    # Raw SQL, not op.create_index(): matches the exact index DDL text
    # app.py's _migrate_users_email_case_insensitive_index produces
    # (CLAUDE-P30) -- explicit COLLATE NOCASE in the index definition
    # itself, not just relying on the column's own declared collation.
    op.execute("CREATE UNIQUE INDEX ix_users_email ON users (email COLLATE NOCASE)")

    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_password_reset_tokens_user_id", "password_reset_tokens", ["user_id"])
    op.create_index("ix_password_reset_tokens_token_hash", "password_reset_tokens", ["token_hash"], unique=True)


def downgrade():
    op.drop_table("password_reset_tokens")
    op.drop_table("users")
