"""Regenerate static/img/archiosk-wordmark.svg (CLAUDE-LANDING-HERO-01A).

The ARCHIOSK wordmark is drawn as vector letterforms rather than set in a
typeface: this repository ships no font assets, has no @font-face and loads
no external font host, and the Product Owner's approved landing reference
calls for a crossbar-less wide upside-down-V for the A, which no web-safe
family provides. Drawing it guarantees the exact letterform everywhere and
adds no dependency, no build step and no external request.

This exists so the wordmark stays adjustable. Spacing, weight and cap height
are parameters here; in the emitted SVG they are ~15 hand-numbered paths,
which is not a safe thing to edit by hand. Change LAYOUT or SW and re-run:

    ./venv/Scripts/python.exe tools/generate_landing_wordmark.py

Run from the repository root. It overwrites the asset in place; check the
diff, and re-check the rendering, before committing.
"""
import io, math

T, B, MID, SW = 22, 102, 62, 14.5   # cap top, baseline, x-height mid, stroke width

def A(x, w=68): return [f"M{x} {B} L{x+w/2:g} {T} L{x+w} {B}"]
def R(x, w=58):
    return [f"M{x} {T} V{B}",
            f"M{x} {T} H{x+38} A21 21 0 0 1 {x+38} 64 H{x}",
            f"M{x+26} 64 L{x+w} {B}"]
def C(x, w=64):
    cx, r = x + w/2, 32
    dx, dy = r*math.cos(math.radians(50)), r*math.sin(math.radians(50))
    return [f"M{cx+dx:.1f} {MID-dy:.1f} A{r} {r} 0 1 0 {cx+dx:.1f} {MID+dy:.1f}"]
def H(x, w=60): return [f"M{x} {T} V{B}", f"M{x+w} {T} V{B}", f"M{x} {MID} H{x+w}"]
def I(x, w=0):  return [f"M{x} {T} V{B}"]
def O(x, w=64): return None  # emitted as <circle>
def S(x, w=48):
    L, Rr, m = x, x + w, x + w/2
    return [f"M{Rr} 38 C{Rr} 28 {Rr-10} {T} {m} {T} C{L+10} {T} {L} 29 {L} 41 "
            f"C{L} 53 {L+10} 58 {m} {MID} C{Rr-10} 66 {Rr} 72 {Rr} 84 "
            f"C{Rr} 95 {Rr-10} {B} {m} {B} C{m-12} {B} {L+1} 97 {L} 87"]
def K(x, w=58): return [f"M{x} {T} V{B}", f"M{x} {MID} L{x+52} {T}", f"M{x} {MID} L{x+w} {B}"]

# x-origins, optically spaced: round letters (C, O) sit tighter to their
# neighbours than flat-sided ones, and the bare I stem gets extra air.
LAYOUT = [("A", A, 20, 68), ("R", R, 112, 58), ("C", C, 196, 64), ("H", H, 278, 60),
          ("I", I, 362, 0),  ("O", O, 386, 64), ("S", S, 474, 48), ("K", K, 548, 58)]

VW = 626
body = []
for name, fn, x, w in LAYOUT:
    body.append(f"    <!-- {name} -->")
    if name == "O":
        body.append(f'    <circle cx="{x + w/2:g}" cy="{MID}" r="32"/>')
    else:
        for d in fn(x, w) if w else fn(x):
            body.append(f'    <path d="{d}"/>')

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {VW} 124" width="{VW}" height="124" role="img" aria-label="ARCHIOSK">
  <title>ARCHIOSK</title>
  <!--
    CLAUDE-LANDING-HERO-01A. The ARCHIOSK wordmark drawn as vector
    letterforms rather than set in a typeface.

    Why geometry and not a font: this repository ships NO font assets, has
    no @font-face and loads no external font host, and the approved
    reference calls for a crossbar-less wide upside-down-V for the A, which
    no web-safe family provides. Drawing it guarantees the exact letterform
    on every device and adds no dependency, no build step and no external
    request, consistent with the constraints tools/dependency_fit.py
    encodes.

    Construction: mono-line geometric skeleton, uniform {SW}-unit stroke,
    butt caps, cap height {B-T} (y {T} to {B}). Letter origins are optically
    spaced, not metrically: the round C and O sit tighter to their
    neighbours than the flat-sided H, and the bare I stem is given extra
    air on both sides. Regenerated by
    tools/generate_landing_wordmark.py; edit the layout there rather than
    nudging path numbers by hand.
  -->
  <defs>
    <!-- userSpaceOnUse, deliberately: H, I and every stem are zero-width
         paths, and an objectBoundingBox gradient cannot paint a zero-area
         bounding box, so those letters silently vanish. Painting in user
         space also makes the whole wordmark read as ONE sheet of metal
         rather than as eight independent per-letter ramps. -->
    <linearGradient id="aw-metal" gradientUnits="userSpaceOnUse" x1="0" y1="18" x2="0" y2="106">
      <stop offset="0%" stop-color="#ffffff"/>
      <stop offset="26%" stop-color="#e8eef4"/>
      <stop offset="50%" stop-color="#9aa6b3"/>
      <stop offset="68%" stop-color="#f7fafc"/>
      <stop offset="100%" stop-color="#c8d2dc"/>
    </linearGradient>
  </defs>

  <g fill="none" stroke="url(#aw-metal)" stroke-width="{SW}"
     stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="6">
{chr(10).join(body)}
  </g>
</svg>
'''
io.open("static/img/archiosk-wordmark.svg", "w", encoding="utf-8", newline="").write(svg)
print("wordmark regenerated")
